Final updates

diff --git a/.github/workflows/Compressor.yml b/.github/workflows/Compressor.yml
--- a/.github/workflows/Compressor.yml
+++ b/.github/workflows/Compressor.yml
@@ -4,7 +4,7 @@ on: [push]
 
 env:
   FILE_URL: https://mirror.rahul137.workers.dev/alpha.zip
-  FILE_NAME: Alpha.apk
+  FILE_NAME:
   TZ: Asia/Kolkata
 jobs:
   build:
@@ -22,16 +22,24 @@ jobs:
          run: |
               mkdir -p file
               cd file
-              echo "Downloading your file. wait... it can take some seconds/minutes"
-              aria2c $FILE_URL
+              if [ -z "$FILE_URL" ]; then
+              echo "Enter url of file to download"
+              exit 1;
+              else echo "Downloading your file. wait... it can take some seconds/minutes"
+              aria2c -c -m 0 $FILE_URL;
+              fi
 
        - name: Decompress File
          run: |
               cd file
               ls
               mkdir -p final
+              if [ -f *.zip ]; then
               echo "Decompressing your file. wait... it will take some seconds"
-              unzip -q *.zip -d ./final
+              unzip -q *.zip -d ./final;
+              else echo "File is not a zip!"
+              exit 1;
+              fi
               cd final
               ls
        
