Final updates

diff --git a/.github/workflows/Compressor.yml b/.github/workflows/Compressor.yml
--- a/.github/workflows/Compressor.yml
+++ b/.github/workflows/Compressor.yml
@@ -21,15 +21,23 @@ jobs:
        - name: Download File
          run: |
               mkdir -p file
-              echo "Downloading your file. wait... it can take some seconds/minutes"
-              aria2c -o "file/$FILE_NAME.zip" $FILE_URL
+              if [ -z "$FILE_URL" ]; then
+              echo "Enter url of file to download"
+              exit 1;
+              else echo "Downloading your file. wait... it can take some seconds/minutes"
+              aria2c -c -m 0 $FILE_URL;
+              fi
 
        - name: Decompress File
          run: |
               cd file
               ls
+              if [ -f *.zip ]; then
               echo "Decompressing your file. wait... it will take some seconds"
-              unzip -q $FILE_NAME
+              unzip -q *.zip ;
+              else echo "File is not a zip!"
+              exit 1;
+              fi
               cd SGSI
               ls
        
@@ -44,7 +52,7 @@ jobs:
               echo "Compressing your file. wait... it can take some minutes"
               if [ -z "$FILE_NAME" ]; 
               then xz -fev9 *; 
-              else xz -cfev9 * > $FILE_NAME.xz ; 
+              else xz -cfev9 * > $FILE_NAME.xz ;
               fi
               ls
 
