Final updates

diff --git a/.github/workflows/Compressor.yml b/.github/workflows/Compressor.yml
--- a/.github/workflows/Compressor.yml
+++ b/.github/workflows/Compressor.yml
@@ -22,8 +22,12 @@ jobs:
          run: |
               mkdir -p file
               cd file
-              echo "Downloading your file. wait... it can take some seconds/minutes"
-              aria2c $FILE_URL
+              if [ -z "$FILE_URL" ]; then
+              echo "Enter url of file to download"
+              exit 1;
+              else echo "Downloading your file. wait... it can take some seconds/minutes"
+              aria2c -c -m 0 $FILE_URL;
+              fi
        
        - name: Compress File
          run: |
